# Generated by Django 3.0.2 on 2020-01-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_remove_player_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='password',
            field=models.IntegerField(default=5073),
        ),
    ]
