# Generated by Django 3.0.2 on 2020-01-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_player_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='password',
            field=models.IntegerField(default=1223),
        ),
    ]
