# Generated by Django 3.0.2 on 2020-01-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_auto_20200122_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='password',
            field=models.IntegerField(),
        ),
    ]
